// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckUVInstalled():Promise<boolean>;

export function GetReadme(arg1:string):Promise<string>;

export function GetRepoInfo(arg1:string):Promise<main.RepoInfo>;

export function GetUVVersion():Promise<string>;

export function InstallApp(arg1:string):Promise<string>;

export function InstallUV():Promise<string>;

export function OpenExternal(arg1:string):Promise<void>;
