// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUVInstalled() {
  return window['go']['main']['App']['CheckUVInstalled']();
}

export function GetReadme(arg1) {
  return window['go']['main']['App']['GetReadme'](arg1);
}

export function GetRepoInfo(arg1) {
  return window['go']['main']['App']['GetRepoInfo'](arg1);
}

export function GetUVVersion() {
  return window['go']['main']['App']['GetUVVersion']();
}

export function InstallApp(arg1) {
  return window['go']['main']['App']['InstallApp'](arg1);
}

export function InstallUV() {
  return window['go']['main']['App']['InstallUV']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}
